//
//  Fixtures.swift
//  DPCredentialsTests
//

import Foundation

/// Test data generated by real OpenSSH tools, not written by hand.
///
/// This distinction matters more than it might appear. A hashed `known_hosts` entry invented to match
/// our own parser proves only that the parser agrees with itself. Every value here came out of
/// `ssh-keygen`, and the expected fingerprint was cross-checked with `ssh-keygen -lf`, so the tests
/// verify agreement with OpenSSH rather than with our assumptions.
///
/// Reproduce with:
/// ```sh
/// ssh-keygen -t ed25519 -N '' -C test -f testkey     # unencrypted
/// ssh-keygen -t ed25519 -N 'secret123' -C enc -f enc_key
/// ssh-keygen -lf testkey.pub                          # the expected fingerprint
/// ssh-keygen -H -f known_hosts                        # hashes the host names
/// ```
enum Fixtures {

    // MARK: - Host key

    /// An Ed25519 public key in `authorized_keys` form.
    static let publicKeyLine =
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG61sTbGdM8BhwOyaTeJQ9oI1fk9ayGp13zFTN0sG5qf test"

    /// The base64 key field on its own.
    static let publicKeyBase64 = "AAAAC3NzaC1lZDI1NTE5AAAAIG61sTbGdM8BhwOyaTeJQ9oI1fk9ayGp13zFTN0sG5qf"

    /// The decoded key blob.
    static var publicKeyBlob: Data { Data(base64Encoded: publicKeyBase64)! }

    /// The fingerprint `ssh-keygen -lf` prints for ``publicKeyLine``, verified by hand.
    ///
    /// If a change to the fingerprint code breaks this constant, the code is wrong — not the constant.
    static let expectedFingerprint = "SHA256:PFM0y4QH3DQRNtkRP9ouT+ORYemBoaskM8VEAgF/GUk"

    /// A second, unrelated Ed25519 key, for testing the changed-key path.
    static let otherPublicKeyBase64 = "AAAAC3NzaC1lZDI1NTE5AAAAICNmfAuScze9rxJYbGdM8BhwOyaTeJQ9oI1fk9ayGp13"

    /// The decoded second key blob.
    static var otherPublicKeyBlob: Data { Data(base64Encoded: otherPublicKeyBase64)! }

    // MARK: - known_hosts

    /// Plain (unhashed) entries for `example.com` and `[localhost]:2222`.
    static let plainKnownHosts = """
        # a comment, and a blank line follow

        example.com ssh-ed25519 \(publicKeyBase64)
        [localhost]:2222 ssh-ed25519 \(publicKeyBase64)
        """

    /// The same two entries after `ssh-keygen -H`, with host names hashed.
    ///
    /// Hashed entries are the default on modern OpenSSH, so a parser that handles only the plain form
    /// matches nothing on a typical machine.
    static let hashedKnownHosts = """
        |1|5f+0pkqR8SVUjmIpMtECqgrkgpk=|emjvQDEorCIONRzGqCthLdlxPkU= ssh-ed25519 \(publicKeyBase64)
        |1|oJRJ9B+tU7FAnTl15ZuLQjUKzi0=|zwRkx6t4njywe7qsDO23FClhxyM= ssh-ed25519 \(publicKeyBase64)
        """

    // MARK: - Private keys

    /// The first lines of an unencrypted OpenSSH key. The cipher field reads `none`.
    static let unencryptedOpenSSHKey = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACButbE2xnTPAYcDsmk3iUPaCNX5PWshqdd8xUzdLBuanwAAAIipZ6kKqWep
        -----END OPENSSH PRIVATE KEY-----
        """

    /// The first lines of an OpenSSH key encrypted with a passphrase. The cipher field reads `aes256-ctr`.
    ///
    /// Note the header is byte-identical to the unencrypted one — which is exactly why the base64 body
    /// has to be decoded rather than the text searched for the word "ENCRYPTED".
    static let encryptedOpenSSHKey = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCHCfGw8R
        imRiPmlk8qFIeqAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAICNmfAuScze9rxJY
        -----END OPENSSH PRIVATE KEY-----
        """

    /// A classic PEM key protected by a passphrase, which advertises the fact in the clear.
    static let encryptedPEMKey = """
        -----BEGIN RSA PRIVATE KEY-----
        Proc-Type: 4,ENCRYPTED
        DEK-Info: AES-128-CBC,0123456789ABCDEF0123456789ABCDEF

        MIIEowIBAAKCAQEA1234567890
        -----END RSA PRIVATE KEY-----
        """
}
